### PR TITLE
Feat/oracle

### PR DESCRIPTION
**Pull request by ihuangxing**
# 解决OpenIdConnect在Oracle环境下出现的问题

1、标识符超出30个字符导致无法执行数据库迁移
2、字段必填问题

## Checklist

本地测试成功执行迁移

### CODE REVIEW

**Comment by doddgu** [comment]
@zhenlei520 @MayueCif  PTAL

**Comment by MayueCif** [comment]
@doddgu LGTM

**Comment by zhenlei520** [comment]
@ihuangxing You should commit merge to main branch, not feat/oracle

**Review by zhenlei520 — CHANGES_REQUESTED** [review]

**Comment by zhenlei520** [comment]
A new pr has been submitted #295 , the current pr is closed

**Pull request closed without merging**
